@startuml

class Individu << Entity >> {
  - id: Bigint
  - nom: String
  - prenom: String
  - civilite: String
  - code_synchro: String
  - telephoneMobile: String
  - telephoneFixe: String
  - email: String
  + getters() et setters()
  + equals()
  + hashCode()
  + toString()
}

class Utilisateur << Entity >> {
   -id: Bigint
   -login: String
   -mdp : String
   + getters() et setters()
   + equals()
   + hashCode()
   + toString()
}

class Division << Entity >> {
   - id: Bigint
   - code: String
   - libelle: String
   + getters() et setters()
   + equals()
   + hashCode()
   + toString()
}

class Niveau << Entity >> {
   - id: Bigint
   - code: String
   - niveauCourt: String
   - niveauLong: String
   + getters() et setters()
   + equals()
   + hashCode()
   + toString()
}

class Discipline << Entity >> {
   - id: Bigint
   - code: String
   - libelle: String
   + getters() et setters()
   + equals()
   + hashCode()
   + toString()
}

class Stagiaire << Entitiy >> {
   - id
   - dateDebut
   - dateFin
   + getters() et setters()
   + equals()
   + hashCode()
   + toString()
}

class Stage << Entitiy >> {
   - id
   - dateDebut
   - dateFin
   + getters() et setters()
   + equals()
   + hashCode()
   + toString()
}

class Entreprise << Entitiy >> {
   - id
   + getters() et setters()
   + equals()
   + hashCode()
   + toString()
}

class Employe << Entitiy >> {
   - id
   + getters() et setters()
   + equals()
   + hashCode()
   + toString()
}

class Visite << Entitiy >> {
   - id
   + getters() et setters()
   + equals()
   + hashCode()
   + toString()
}

class Template << Entitiy >> {
   - id
   + getters() et setters()
   + equals()
   + hashCode()
   + toString()
}

hide circle
hide methods

Individu  "*" -left--- "*" Stage
(Individu, Stage) .. Stagiaire

Individu "0..1" --- "0..1" Utilisateur
Individu "*" ---> "*" Division
Individu " *   " ---> " * " Discipline
Division "0..*" --- "0..1" Niveau
Visite "0..*" --- "1 " Stage
Visite "0..*" --- "0..1" Individu
Stagiaire "*" --- "tuteur 1" Employe
Employe "0..*" --- "0..1" Entreprise
Stage "*" --- "1 responsable" Entreprise
Stage "*" -left--- "1 referent" Individu
@enduml
